swagger-editor:
  image: swaggerapi/swagger-editor
  container_name: "test-swagger-editor"
  ports:
    - "9091:8080"

swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: "test-swagger-ui"
  ports:
    - "9092:8080"
  volumes:
    - ./hoge.yml:/hoge.yml
    - ./test.yml:/test.yml
  environment:
    SWAGGER_JSON: /test.yml
